zoo-class-created
jalileus/Java-tasks pull request #5
Opened 2024-11-03 00:38 UTC by jalileus

2024-11-12 11:52 UTC, jalileus commented
Name : Alhajali Jalal

2024-12-09 23:22 UTC, DmitrySteblovskiy requested changes
Actually, ur code seems to be fine, but u certainly have to use .gitignore and get rid of unnecessary files in MR - to my mind it is both essential and easy-to-do.

2024-12-09 23:22 UTC, DmitrySteblovskiy commented on zoo-task/ZOO'/.vscode/settings.json
> +{
unnecessary files in MR, add the .vscode dir to .gitignore

2024-12-09 23:22 UTC, DmitrySteblovskiy commented on zoo-task/ZOO'/bin/Animal.class
no binaries in MR...
Use gitignore

2025-02-08 16:35 UTC, merged